### ISSUE TITLE
Alternative microcontroller

### ISSUE THREAD

**Issue by dwbridgfoot** [develin4000/joydivision#1]
Hi,
It seems I am unable to find a ATMEGA8-8AU microcontroller anywhere.

Closest I can find is either:
ATMEGA8A-AU  (MCU AVR 8KB, 512B EE **16MHz** 1KB SRAM 2.7 - 5.5V)
or
ATMEGA8L-8AU (MCU AVR 8KB, 512B EE **8MHz** 1KB SRAM 2.7 - 5.5V)

Should it be 8MHz or 16MHz or doesn't it matter?

Thanks,

**Comment by develin4000** [comment]
Hi there,

The limitations are set by V-USB stack which is used for this project, so the 16Mhz you found should be working. 


"Runs on any AVR microcontroller with at least 2 kB of Flash memory, 128 bytes RAM and a clock rate of at least 12 MHz."

Source : https://www.obdev.at/products/vusb/index.html

/ Stefan

**Comment by dwbridgfoot** [comment]
Great, thanks for confirming.
